# Generated by Django 2.2.14 on 2021-05-26 10:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShpNepal',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('descriptio', models.CharField(blank=True, max_length=1, null=True)),
                ('name', models.CharField(blank=True, max_length=1, null=True)),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('dist_code', models.IntegerField(blank=True, null=True)),
                ('dist_name', models.CharField(blank=True, max_length=14, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_len', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('cartodb_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shp_Nepal',
                'managed': False,
            },
        ),
    ]
